# Generated by Django 5.2.4 on 2025-07-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_products_image_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='picture',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='', upload_to='products/'),
            preserve_default=False,
        ),
    ]
