# Generated by Django 5.2.4 on 2025-07-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='invoice',
        ),
    ]
